export const SETTINGS = {
    PROFILE: "PROFILE"
}

export const PROFILE = {
    POSTS: "POSTS",
    HIDDEN_POSTS: "HIDDEN_POSTS",
    COMMENTS: "COMMENTS",
    FOLLOWERS: "FOLLOWERS",
    FOLLOWING: "FOLLOWING",
}